name = "docker"
account_id = "da801d4ac962339bd8c7a26fbdffe719"
main = "src/index.ts"
compatibility_date = "2024-06-08"

workers_dev = true
routes = [
    { pattern = "docker.c332030.com/*", zone_name = "c332030.com" },
]

kv_namespaces = [
    { binding = "HAMMAL_CACHE", id = "8c2f0d76cf0e4f2da99ab3c438cee826" }
]
